### ISSUE TITLE
302 Redirect

### ISSUE THREAD

**Issue by 130nk3r5** [EngelEatos/cloudflare-scrape#1]
Does not solve the 302 redirect issue?

**Comment by EngelEatos** [comment]
maybe outdated? I don't know I'm not using it anymore.

**Comment by 130nk3r5** [comment]
That's a shame.... What are you using?

**Comment by EngelEatos** [comment]
I use python for scraping most of them time and then I'm using the original project https://github.com/Anorov/cloudflare-scrape

**Comment by 130nk3r5** [comment]
Ah, that helps. Thanks
